package com.github.mouse0w0.peach.mcmod.generator.v1_12_2.bytecode.block;

import com.github.mouse0w0.peach.mcmod.generator.util.ASMUtils;
import com.github.mouse0w0.peach.mcmod.generator.v1_12_2.bytecode.ClassGenerator;
import org.objectweb.asm.AnnotationVisitor;
import org.objectweb.asm.FieldVisitor;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;

import static org.objectweb.asm.Opcodes.*;

public class BlockWallBase extends ClassGenerator {
    public BlockWallBase(String className) {
        super(className);

        FieldVisitor fv;
        MethodVisitor mv;
        AnnotationVisitor av;

        cw.visit(V1_8, ACC_PUBLIC | ACC_SUPER, className, null, "net/minecraft/block/Block", null);

        ASMUtils.visitSource(cw);

        {
            fv = cw.visitField(ACC_PUBLIC | ACC_FINAL | ACC_STATIC, "UP", "Lnet/minecraft/block/properties/PropertyBool;", null, null);
            fv.visitEnd();
        }
        {
            fv = cw.visitField(ACC_PUBLIC | ACC_FINAL | ACC_STATIC, "NORTH", "Lnet/minecraft/block/properties/PropertyBool;", null, null);
            fv.visitEnd();
        }
        {
            fv = cw.visitField(ACC_PUBLIC | ACC_FINAL | ACC_STATIC, "EAST", "Lnet/minecraft/block/properties/PropertyBool;", null, null);
            fv.visitEnd();
        }
        {
            fv = cw.visitField(ACC_PUBLIC | ACC_FINAL | ACC_STATIC, "SOUTH", "Lnet/minecraft/block/properties/PropertyBool;", null, null);
            fv.visitEnd();
        }
        {
            fv = cw.visitField(ACC_PUBLIC | ACC_FINAL | ACC_STATIC, "WEST", "Lnet/minecraft/block/properties/PropertyBool;", null, null);
            fv.visitEnd();
        }
        {
            fv = cw.visitField(ACC_PROTECTED | ACC_FINAL | ACC_STATIC, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;", null, null);
            fv.visitEnd();
        }
        {
            fv = cw.visitField(ACC_PROTECTED | ACC_FINAL | ACC_STATIC, "CLIP_AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;", null, null);
            fv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "<init>", "(Lnet/minecraft/block/material/Material;Lnet/minecraft/block/material/MapColor;)V", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/block/Block", "<init>", "(Lnet/minecraft/block/material/Material;Lnet/minecraft/block/material/MapColor;)V", false);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitFieldInsn(GETFIELD, className, "field_176227_L", "Lnet/minecraft/block/state/BlockStateContainer;");
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/block/state/BlockStateContainer", "func_177621_b", "()Lnet/minecraft/block/state/IBlockState;", false);
            mv.visitFieldInsn(GETSTATIC, className, "UP", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitInsn(ICONST_0);
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177226_a", "(Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitFieldInsn(GETSTATIC, className, "NORTH", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitInsn(ICONST_0);
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177226_a", "(Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitFieldInsn(GETSTATIC, className, "EAST", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitInsn(ICONST_0);
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177226_a", "(Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitFieldInsn(GETSTATIC, className, "SOUTH", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitInsn(ICONST_0);
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177226_a", "(Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitFieldInsn(GETSTATIC, className, "WEST", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitInsn(ICONST_0);
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177226_a", "(Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitMethodInsn(INVOKEVIRTUAL, className, "func_180632_j", "(Lnet/minecraft/block/state/IBlockState;)V", false);
            mv.visitInsn(RETURN);
            mv.visitMaxs(4, 3);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "func_185496_a", "(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/util/math/AxisAlignedBB;", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitMethodInsn(INVOKEVIRTUAL, className, "func_176221_a", "(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/block/state/IBlockState;", false);
            mv.visitVarInsn(ASTORE, 1);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitVarInsn(ALOAD, 1);
            mv.visitMethodInsn(INVOKESTATIC, className, "getAABBIndex", "(Lnet/minecraft/block/state/IBlockState;)I", false);
            mv.visitInsn(AALOAD);
            mv.visitInsn(ARETURN);
            mv.visitMaxs(4, 4);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "func_185477_a", "(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/AxisAlignedBB;Ljava/util/List;Lnet/minecraft/entity/Entity;Z)V", "(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/AxisAlignedBB;Ljava/util/List<Lnet/minecraft/util/math/AxisAlignedBB;>;Lnet/minecraft/entity/Entity;Z)V", null);
            mv.visitAnnotableParameterCount(7, true);
            {
                av = mv.visitParameterAnnotation(5, "Ljavax/annotation/Nullable;", true);
                av.visitEnd();
            }
            mv.visitCode();
            mv.visitVarInsn(ILOAD, 7);
            Label label0 = new Label();
            mv.visitJumpInsn(IFNE, label0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitMethodInsn(INVOKEVIRTUAL, className, "func_176221_a", "(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/block/state/IBlockState;", false);
            mv.visitVarInsn(ASTORE, 1);
            mv.visitLabel(label0);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitVarInsn(ALOAD, 4);
            mv.visitVarInsn(ALOAD, 5);
            mv.visitFieldInsn(GETSTATIC, className, "CLIP_AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitVarInsn(ALOAD, 1);
            mv.visitMethodInsn(INVOKESTATIC, className, "getAABBIndex", "(Lnet/minecraft/block/state/IBlockState;)I", false);
            mv.visitInsn(AALOAD);
            mv.visitMethodInsn(INVOKESTATIC, className, "func_185492_a", "(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/AxisAlignedBB;Ljava/util/List;Lnet/minecraft/util/math/AxisAlignedBB;)V", false);
            mv.visitInsn(RETURN);
            mv.visitMaxs(5, 8);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "func_180646_a", "(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/util/math/AxisAlignedBB;", null, null);
            {
                av = mv.visitAnnotation("Ljavax/annotation/Nullable;", true);
                av.visitEnd();
            }
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitMethodInsn(INVOKEVIRTUAL, className, "func_176221_a", "(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/block/state/IBlockState;", false);
            mv.visitVarInsn(ASTORE, 1);
            mv.visitFieldInsn(GETSTATIC, className, "CLIP_AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitVarInsn(ALOAD, 1);
            mv.visitMethodInsn(INVOKESTATIC, className, "getAABBIndex", "(Lnet/minecraft/block/state/IBlockState;)I", false);
            mv.visitInsn(AALOAD);
            mv.visitInsn(ARETURN);
            mv.visitMaxs(4, 4);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PRIVATE | ACC_STATIC, "getAABBIndex", "(Lnet/minecraft/block/state/IBlockState;)I", null, null);
            mv.visitCode();
            mv.visitInsn(ICONST_0);
            mv.visitVarInsn(ISTORE, 1);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitFieldInsn(GETSTATIC, className, "NORTH", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177229_b", "(Lnet/minecraft/block/properties/IProperty;)Ljava/lang/Comparable;", true);
            mv.visitTypeInsn(CHECKCAST, "java/lang/Boolean");
            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Boolean", "booleanValue", "()Z", false);
            Label label0 = new Label();
            mv.visitJumpInsn(IFEQ, label0);
            mv.visitVarInsn(ILOAD, 1);
            mv.visitInsn(ICONST_1);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "NORTH", "Lnet/minecraft/util/EnumFacing;");
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/EnumFacing", "func_176736_b", "()I", false);
            mv.visitInsn(ISHL);
            mv.visitInsn(IOR);
            mv.visitVarInsn(ISTORE, 1);
            mv.visitLabel(label0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitFieldInsn(GETSTATIC, className, "EAST", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177229_b", "(Lnet/minecraft/block/properties/IProperty;)Ljava/lang/Comparable;", true);
            mv.visitTypeInsn(CHECKCAST, "java/lang/Boolean");
            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Boolean", "booleanValue", "()Z", false);
            Label label1 = new Label();
            mv.visitJumpInsn(IFEQ, label1);
            mv.visitVarInsn(ILOAD, 1);
            mv.visitInsn(ICONST_1);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "EAST", "Lnet/minecraft/util/EnumFacing;");
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/EnumFacing", "func_176736_b", "()I", false);
            mv.visitInsn(ISHL);
            mv.visitInsn(IOR);
            mv.visitVarInsn(ISTORE, 1);
            mv.visitLabel(label1);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitFieldInsn(GETSTATIC, className, "SOUTH", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177229_b", "(Lnet/minecraft/block/properties/IProperty;)Ljava/lang/Comparable;", true);
            mv.visitTypeInsn(CHECKCAST, "java/lang/Boolean");
            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Boolean", "booleanValue", "()Z", false);
            Label label2 = new Label();
            mv.visitJumpInsn(IFEQ, label2);
            mv.visitVarInsn(ILOAD, 1);
            mv.visitInsn(ICONST_1);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "SOUTH", "Lnet/minecraft/util/EnumFacing;");
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/EnumFacing", "func_176736_b", "()I", false);
            mv.visitInsn(ISHL);
            mv.visitInsn(IOR);
            mv.visitVarInsn(ISTORE, 1);
            mv.visitLabel(label2);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitFieldInsn(GETSTATIC, className, "WEST", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177229_b", "(Lnet/minecraft/block/properties/IProperty;)Ljava/lang/Comparable;", true);
            mv.visitTypeInsn(CHECKCAST, "java/lang/Boolean");
            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Boolean", "booleanValue", "()Z", false);
            Label label3 = new Label();
            mv.visitJumpInsn(IFEQ, label3);
            mv.visitVarInsn(ILOAD, 1);
            mv.visitInsn(ICONST_1);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "WEST", "Lnet/minecraft/util/EnumFacing;");
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/EnumFacing", "func_176736_b", "()I", false);
            mv.visitInsn(ISHL);
            mv.visitInsn(IOR);
            mv.visitVarInsn(ISTORE, 1);
            mv.visitLabel(label3);
            mv.visitVarInsn(ILOAD, 1);
            mv.visitInsn(IRETURN);
            mv.visitMaxs(3, 2);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "func_149686_d", "(Lnet/minecraft/block/state/IBlockState;)Z", null, null);
            mv.visitCode();
            mv.visitInsn(ICONST_0);
            mv.visitInsn(IRETURN);
            mv.visitMaxs(1, 2);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "func_176205_b", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;)Z", null, null);
            mv.visitCode();
            mv.visitInsn(ICONST_0);
            mv.visitInsn(IRETURN);
            mv.visitMaxs(1, 3);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "func_149662_c", "(Lnet/minecraft/block/state/IBlockState;)Z", null, null);
            mv.visitCode();
            mv.visitInsn(ICONST_0);
            mv.visitInsn(IRETURN);
            mv.visitMaxs(1, 2);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PRIVATE, "canConnectTo", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/world/IBlockAccess", "func_180495_p", "(Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitVarInsn(ASTORE, 4);
            mv.visitVarInsn(ALOAD, 4);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177230_c", "()Lnet/minecraft/block/Block;", true);
            mv.visitVarInsn(ASTORE, 5);
            mv.visitVarInsn(ALOAD, 4);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_193401_d", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Lnet/minecraft/block/state/BlockFaceShape;", true);
            mv.visitVarInsn(ASTORE, 6);
            mv.visitVarInsn(ALOAD, 6);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/block/state/BlockFaceShape", "MIDDLE_POLE_THICK", "Lnet/minecraft/block/state/BlockFaceShape;");
            Label label0 = new Label();
            mv.visitJumpInsn(IF_ACMPEQ, label0);
            mv.visitVarInsn(ALOAD, 6);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/block/state/BlockFaceShape", "MIDDLE_POLE", "Lnet/minecraft/block/state/BlockFaceShape;");
            Label label1 = new Label();
            mv.visitJumpInsn(IF_ACMPNE, label1);
            mv.visitVarInsn(ALOAD, 5);
            mv.visitTypeInsn(INSTANCEOF, "net/minecraft/block/BlockFenceGate");
            mv.visitJumpInsn(IFEQ, label1);
            mv.visitLabel(label0);
            mv.visitInsn(ICONST_1);
            Label label2 = new Label();
            mv.visitJumpInsn(GOTO, label2);
            mv.visitLabel(label1);
            mv.visitInsn(ICONST_0);
            mv.visitLabel(label2);
            mv.visitVarInsn(ISTORE, 7);
            mv.visitVarInsn(ALOAD, 5);
            mv.visitMethodInsn(INVOKESTATIC, className, "isExcepBlockForAttachWithPiston", "(Lnet/minecraft/block/Block;)Z", false);
            Label label3 = new Label();
            mv.visitJumpInsn(IFNE, label3);
            mv.visitVarInsn(ALOAD, 6);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/block/state/BlockFaceShape", "SOLID", "Lnet/minecraft/block/state/BlockFaceShape;");
            Label label4 = new Label();
            mv.visitJumpInsn(IF_ACMPEQ, label4);
            mv.visitLabel(label3);
            mv.visitVarInsn(ILOAD, 7);
            Label label5 = new Label();
            mv.visitJumpInsn(IFEQ, label5);
            mv.visitLabel(label4);
            mv.visitInsn(ICONST_1);
            Label label6 = new Label();
            mv.visitJumpInsn(GOTO, label6);
            mv.visitLabel(label5);
            mv.visitInsn(ICONST_0);
            mv.visitLabel(label6);
            mv.visitInsn(IRETURN);
            mv.visitMaxs(4, 8);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PROTECTED | ACC_STATIC, "isExcepBlockForAttachWithPiston", "(Lnet/minecraft/block/Block;)Z", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 0);
            mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/block/Block", "func_193382_c", "(Lnet/minecraft/block/Block;)Z", false);
            Label label0 = new Label();
            mv.visitJumpInsn(IFNE, label0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/init/Blocks", "field_180401_cv", "Lnet/minecraft/block/Block;");
            mv.visitJumpInsn(IF_ACMPEQ, label0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/init/Blocks", "field_150440_ba", "Lnet/minecraft/block/Block;");
            mv.visitJumpInsn(IF_ACMPEQ, label0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/init/Blocks", "field_150423_aK", "Lnet/minecraft/block/Block;");
            mv.visitJumpInsn(IF_ACMPEQ, label0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/init/Blocks", "field_150428_aP", "Lnet/minecraft/block/Block;");
            Label label1 = new Label();
            mv.visitJumpInsn(IF_ACMPNE, label1);
            mv.visitLabel(label0);
            mv.visitInsn(ICONST_1);
            Label label2 = new Label();
            mv.visitJumpInsn(GOTO, label2);
            mv.visitLabel(label1);
            mv.visitInsn(ICONST_0);
            mv.visitLabel(label2);
            mv.visitInsn(IRETURN);
            mv.visitMaxs(2, 1);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "func_176225_a", "(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", null, null);
            {
                av = mv.visitAnnotation("Lnet/minecraftforge/fml/relauncher/SideOnly;", true);
                av.visitEnum("value", "Lnet/minecraftforge/fml/relauncher/Side;", "CLIENT");
                av.visitEnd();
            }
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 4);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "DOWN", "Lnet/minecraft/util/EnumFacing;");
            Label label0 = new Label();
            mv.visitJumpInsn(IF_ACMPNE, label0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitVarInsn(ALOAD, 4);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/block/Block", "func_176225_a", "(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", false);
            Label label1 = new Label();
            mv.visitJumpInsn(IFEQ, label1);
            mv.visitLabel(label0);
            mv.visitInsn(ICONST_1);
            Label label2 = new Label();
            mv.visitJumpInsn(GOTO, label2);
            mv.visitLabel(label1);
            mv.visitInsn(ICONST_0);
            mv.visitLabel(label2);
            mv.visitInsn(IRETURN);
            mv.visitMaxs(5, 5);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "func_176221_a", "(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/block/state/IBlockState;", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "NORTH", "Lnet/minecraft/util/EnumFacing;");
            mv.visitMethodInsn(INVOKESPECIAL, className, "canWallConnectTo", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", false);
            mv.visitVarInsn(ISTORE, 4);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "EAST", "Lnet/minecraft/util/EnumFacing;");
            mv.visitMethodInsn(INVOKESPECIAL, className, "canWallConnectTo", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", false);
            mv.visitVarInsn(ISTORE, 5);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "SOUTH", "Lnet/minecraft/util/EnumFacing;");
            mv.visitMethodInsn(INVOKESPECIAL, className, "canWallConnectTo", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", false);
            mv.visitVarInsn(ISTORE, 6);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "WEST", "Lnet/minecraft/util/EnumFacing;");
            mv.visitMethodInsn(INVOKESPECIAL, className, "canWallConnectTo", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", false);
            mv.visitVarInsn(ISTORE, 7);
            mv.visitVarInsn(ILOAD, 4);
            Label label0 = new Label();
            mv.visitJumpInsn(IFEQ, label0);
            mv.visitVarInsn(ILOAD, 5);
            mv.visitJumpInsn(IFNE, label0);
            mv.visitVarInsn(ILOAD, 6);
            mv.visitJumpInsn(IFEQ, label0);
            mv.visitVarInsn(ILOAD, 7);
            Label label1 = new Label();
            mv.visitJumpInsn(IFEQ, label1);
            mv.visitLabel(label0);
            mv.visitVarInsn(ILOAD, 4);
            Label label2 = new Label();
            mv.visitJumpInsn(IFNE, label2);
            mv.visitVarInsn(ILOAD, 5);
            mv.visitJumpInsn(IFEQ, label2);
            mv.visitVarInsn(ILOAD, 6);
            mv.visitJumpInsn(IFNE, label2);
            mv.visitVarInsn(ILOAD, 7);
            mv.visitJumpInsn(IFEQ, label2);
            mv.visitLabel(label1);
            mv.visitInsn(ICONST_1);
            Label label3 = new Label();
            mv.visitJumpInsn(GOTO, label3);
            mv.visitLabel(label2);
            mv.visitInsn(ICONST_0);
            mv.visitLabel(label3);
            mv.visitVarInsn(ISTORE, 8);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitFieldInsn(GETSTATIC, className, "UP", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitVarInsn(ILOAD, 8);
            Label label4 = new Label();
            mv.visitJumpInsn(IFEQ, label4);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/BlockPos", "func_177984_a", "()Lnet/minecraft/util/math/BlockPos;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/world/IBlockAccess", "func_175623_d", "(Lnet/minecraft/util/math/BlockPos;)Z", true);
            Label label5 = new Label();
            mv.visitJumpInsn(IFNE, label5);
            mv.visitLabel(label4);
            mv.visitInsn(ICONST_1);
            Label label6 = new Label();
            mv.visitJumpInsn(GOTO, label6);
            mv.visitLabel(label5);
            mv.visitInsn(ICONST_0);
            mv.visitLabel(label6);
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177226_a", "(Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitFieldInsn(GETSTATIC, className, "NORTH", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitVarInsn(ILOAD, 4);
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177226_a", "(Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitFieldInsn(GETSTATIC, className, "EAST", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitVarInsn(ILOAD, 5);
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177226_a", "(Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitFieldInsn(GETSTATIC, className, "SOUTH", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitVarInsn(ILOAD, 6);
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177226_a", "(Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitFieldInsn(GETSTATIC, className, "WEST", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitVarInsn(ILOAD, 7);
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;", false);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177226_a", "(Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitInsn(ARETURN);
            mv.visitMaxs(4, 9);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PROTECTED, "func_180661_e", "()Lnet/minecraft/block/state/BlockStateContainer;", null, null);
            mv.visitCode();
            mv.visitTypeInsn(NEW, "net/minecraft/block/state/BlockStateContainer");
            mv.visitInsn(DUP);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitInsn(ICONST_5);
            mv.visitTypeInsn(ANEWARRAY, "net/minecraft/block/properties/IProperty");
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_0);
            mv.visitFieldInsn(GETSTATIC, className, "UP", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_1);
            mv.visitFieldInsn(GETSTATIC, className, "NORTH", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_2);
            mv.visitFieldInsn(GETSTATIC, className, "EAST", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_3);
            mv.visitFieldInsn(GETSTATIC, className, "WEST", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_4);
            mv.visitFieldInsn(GETSTATIC, className, "SOUTH", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitInsn(AASTORE);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/block/state/BlockStateContainer", "<init>", "(Lnet/minecraft/block/Block;[Lnet/minecraft/block/properties/IProperty;)V", false);
            mv.visitInsn(ARETURN);
            mv.visitMaxs(7, 1);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "func_193383_a", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Lnet/minecraft/block/state/BlockFaceShape;", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 4);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "UP", "Lnet/minecraft/util/EnumFacing;");
            Label label0 = new Label();
            mv.visitJumpInsn(IF_ACMPEQ, label0);
            mv.visitVarInsn(ALOAD, 4);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/util/EnumFacing", "DOWN", "Lnet/minecraft/util/EnumFacing;");
            mv.visitJumpInsn(IF_ACMPEQ, label0);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/block/state/BlockFaceShape", "MIDDLE_POLE_THICK", "Lnet/minecraft/block/state/BlockFaceShape;");
            Label label1 = new Label();
            mv.visitJumpInsn(GOTO, label1);
            mv.visitLabel(label0);
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/block/state/BlockFaceShape", "CENTER_BIG", "Lnet/minecraft/block/state/BlockFaceShape;");
            mv.visitLabel(label1);
            mv.visitInsn(ARETURN);
            mv.visitMaxs(2, 5);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PUBLIC, "canBeConnectedTo", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/BlockPos", "func_177972_a", "(Lnet/minecraft/util/EnumFacing;)Lnet/minecraft/util/math/BlockPos;", false);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/EnumFacing", "func_176734_d", "()Lnet/minecraft/util/EnumFacing;", false);
            mv.visitMethodInsn(INVOKESPECIAL, className, "canConnectTo", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", false);
            mv.visitInsn(IRETURN);
            mv.visitMaxs(4, 4);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_PRIVATE, "canWallConnectTo", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", null, null);
            mv.visitCode();
            mv.visitVarInsn(ALOAD, 2);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/BlockPos", "func_177972_a", "(Lnet/minecraft/util/EnumFacing;)Lnet/minecraft/util/math/BlockPos;", false);
            mv.visitVarInsn(ASTORE, 4);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 4);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/world/IBlockAccess", "func_180495_p", "(Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/block/state/IBlockState;", true);
            mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/block/state/IBlockState", "func_177230_c", "()Lnet/minecraft/block/Block;", true);
            mv.visitVarInsn(ASTORE, 5);
            mv.visitVarInsn(ALOAD, 5);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 4);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/EnumFacing", "func_176734_d", "()Lnet/minecraft/util/EnumFacing;", false);
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/block/Block", "canBeConnectedTo", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", false);
            Label label0 = new Label();
            mv.visitJumpInsn(IFNE, label0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(ALOAD, 1);
            mv.visitVarInsn(ALOAD, 4);
            mv.visitVarInsn(ALOAD, 3);
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/EnumFacing", "func_176734_d", "()Lnet/minecraft/util/EnumFacing;", false);
            mv.visitMethodInsn(INVOKESPECIAL, className, "canConnectTo", "(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z", false);
            Label label1 = new Label();
            mv.visitJumpInsn(IFEQ, label1);
            mv.visitLabel(label0);
            mv.visitInsn(ICONST_1);
            Label label2 = new Label();
            mv.visitJumpInsn(GOTO, label2);
            mv.visitLabel(label1);
            mv.visitInsn(ICONST_0);
            mv.visitLabel(label2);
            mv.visitInsn(IRETURN);
            mv.visitMaxs(4, 6);
            mv.visitEnd();
        }
        {
            mv = cw.visitMethod(ACC_STATIC, "<clinit>", "()V", null, null);
            mv.visitCode();
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/block/BlockWall", "field_176256_a", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitFieldInsn(PUTSTATIC, className, "UP", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/block/BlockWall", "field_176254_b", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitFieldInsn(PUTSTATIC, className, "NORTH", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/block/BlockWall", "field_176257_M", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitFieldInsn(PUTSTATIC, className, "EAST", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/block/BlockWall", "field_176258_N", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitFieldInsn(PUTSTATIC, className, "SOUTH", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitFieldInsn(GETSTATIC, "net/minecraft/block/BlockWall", "field_176259_O", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitFieldInsn(PUTSTATIC, className, "WEST", "Lnet/minecraft/block/properties/PropertyBool;");
            mv.visitIntInsn(BIPUSH, 16);
            mv.visitTypeInsn(ANEWARRAY, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_0);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitInsn(DCONST_1);
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_1);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_2);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitInsn(DCONST_1);
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_3);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_4);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitInsn(DCONST_1);
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_5);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitLdcInsn(new Double("0.3125"));
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.6875"));
            mv.visitLdcInsn(new Double("0.875"));
            mv.visitInsn(DCONST_1);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 6);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitInsn(DCONST_1);
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 7);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 8);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 9);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 10);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.3125"));
            mv.visitInsn(DCONST_1);
            mv.visitLdcInsn(new Double("0.875"));
            mv.visitLdcInsn(new Double("0.6875"));
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 11);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 12);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 13);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitLdcInsn(new Double("0.25"));
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 14);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitLdcInsn(new Double("0.75"));
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 15);
            mv.visitTypeInsn(NEW, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_0);
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitInsn(DCONST_1);
            mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/math/AxisAlignedBB", "<init>", "(DDDDDD)V", false);
            mv.visitInsn(AASTORE);
            mv.visitFieldInsn(PUTSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 16);
            mv.visitTypeInsn(ANEWARRAY, "net/minecraft/util/math/AxisAlignedBB");
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_0);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitInsn(ICONST_0);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_1);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitInsn(ICONST_1);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_2);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitInsn(ICONST_2);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_3);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitInsn(ICONST_3);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_4);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitInsn(ICONST_4);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitInsn(ICONST_5);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitInsn(ICONST_5);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 6);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 6);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 7);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 7);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 8);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 8);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 9);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 9);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 10);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 10);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 11);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 11);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 12);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 12);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 13);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 13);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 14);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 14);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitInsn(DUP);
            mv.visitIntInsn(BIPUSH, 15);
            mv.visitFieldInsn(GETSTATIC, className, "AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitIntInsn(BIPUSH, 15);
            mv.visitInsn(AALOAD);
            mv.visitLdcInsn(new Double("1.5"));
            mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/AxisAlignedBB", "func_186666_e", "(D)Lnet/minecraft/util/math/AxisAlignedBB;", false);
            mv.visitInsn(AASTORE);
            mv.visitFieldInsn(PUTSTATIC, className, "CLIP_AABB_BY_INDEX", "[Lnet/minecraft/util/math/AxisAlignedBB;");
            mv.visitInsn(RETURN);
            mv.visitMaxs(17, 0);
            mv.visitEnd();
        }
        cw.visitEnd();
    }
}
