package com.github.mouse0w0.peach.mcmod.compiler.v1_12_2;

import com.github.mouse0w0.peach.mcmod.compiler.Context;
import com.github.mouse0w0.peach.mcmod.compiler.task.Task;
import com.github.mouse0w0.peach.mcmod.element.Element;
import com.github.mouse0w0.peach.mcmod.element.LocalizableElement;

import java.io.BufferedWriter;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;

public class GenLanguage implements Task {
    @Override
    public void run(Context context) throws Exception {
        Locale language = context.getMetadata().getLanguage();
        String languageTag = language.getLanguage().toLowerCase() + "_" + language.getCountry().toLowerCase();
        try (BufferedWriter writer = context.getAssetsFiler().newWriter("lang/" + languageTag + ".lang")) {
            String namespace = context.getMetadata().getId();
            Properties translation = new Properties();
            Map<String, String> temp = new HashMap<>();
            for (Element element : context.getElements().values()) {
                if (element instanceof LocalizableElement) {
                    temp.clear();
                    ((LocalizableElement) element).getTranslation(namespace, temp);
                    translation.putAll(temp);
                }
            }
            translation.store(writer, "Generated by Peach.");
        }
    }
}
