package com.github.mouse0w0.peach.mcmod.compiler.v1_12_2;

import com.github.mouse0w0.peach.mcmod.compiler.CompileTask;
import com.github.mouse0w0.peach.mcmod.compiler.Environment;
import com.github.mouse0w0.peach.mcmod.language.LanguageGenerator;

import java.io.BufferedWriter;
import java.util.Locale;

public class LanguageTask implements CompileTask {
    @Override
    public void run(Environment environment) throws Exception {
        Locale language = environment.getModSettings().getLanguage();
        String languageTag = language.getLanguage().toLowerCase() + "_" + language.getCountry().toLowerCase();
        try (BufferedWriter writer = environment.getAssetsFiler().newWriter("lang/" + languageTag + ".json")) {
            LanguageGenerator.generate(environment.getModSettings().getId(), environment.getElements().values())
                    .store(writer, "Generated by Peach.");
        }
    }
}
