package com.github.mouse0w0.peach.mcmod.compiler.v1_12_2;

import com.github.mouse0w0.peach.mcmod.compiler.CompileTask;
import com.github.mouse0w0.peach.mcmod.compiler.Compiler;
import com.github.mouse0w0.peach.mcmod.language.LanguageGenerator;

import java.io.BufferedWriter;
import java.util.Locale;

public class LanguageTask implements CompileTask {
    @Override
    public void run(Compiler compiler) throws Exception {
        Locale language = compiler.getMetadata().getLanguage();
        String languageTag = language.getLanguage().toLowerCase() + "_" + language.getCountry().toLowerCase();
        try (BufferedWriter writer = compiler.getAssetsFiler().newWriter("lang/" + languageTag + ".lang")) {
            LanguageGenerator.generate(compiler.getMetadata().getId(), compiler.getElements().values())
                    .store(writer, "Generated by Peach.");
        }
    }
}
